//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioWebRonnyCliente.ServicioWebAreas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioWebAreas.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCuadrado", ReplyAction="*")]
        decimal AreaCuadrado(decimal n1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCuadrado", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> AreaCuadradoAsync(decimal n1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaTriangulo", ReplyAction="*")]
        decimal AreaTriangulo(decimal n1, decimal n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaTriangulo", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> AreaTrianguloAsync(decimal n1, decimal n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCirculo", ReplyAction="*")]
        decimal AreaCirculo(decimal n1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCirculo", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> AreaCirculoAsync(decimal n1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ServicioWebRonnyCliente.ServicioWebAreas.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ServicioWebRonnyCliente.ServicioWebAreas.WebService1Soap>, ServicioWebRonnyCliente.ServicioWebAreas.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal AreaCuadrado(decimal n1) {
            return base.Channel.AreaCuadrado(n1);
        }
        
        public System.Threading.Tasks.Task<decimal> AreaCuadradoAsync(decimal n1) {
            return base.Channel.AreaCuadradoAsync(n1);
        }
        
        public decimal AreaTriangulo(decimal n1, decimal n2) {
            return base.Channel.AreaTriangulo(n1, n2);
        }
        
        public System.Threading.Tasks.Task<decimal> AreaTrianguloAsync(decimal n1, decimal n2) {
            return base.Channel.AreaTrianguloAsync(n1, n2);
        }
        
        public decimal AreaCirculo(decimal n1) {
            return base.Channel.AreaCirculo(n1);
        }
        
        public System.Threading.Tasks.Task<decimal> AreaCirculoAsync(decimal n1) {
            return base.Channel.AreaCirculoAsync(n1);
        }
    }
}
